server:
  port: 8001

spring:
  application:
    name: Changan-Mall-Order-Edge
  #配置Nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#  配置zipkin 监控
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      #采样值介于0到1之间，1则代表全部采样
#      probability: 1



#  暴露服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"




